        import java.sql.*;
        import Project.ConnectionProvider;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ROHAN
 */
public class AllStudentResult extends javax.swing.JFrame {

    /**
     * Creates new form AllStudentResult
     */
    public AllStudentResult() {
        initComponents();
        show_users();
//        show_user2();


//        try
//        {Connection con = ConnectionProvider.getCon();
//         Statement st = con.createStatement();
//         ResultSet rs = st.executeQuery("select *from students");
//         jTable2.setAutoResizeMode(jTable2.AUTO_RESIZE_OFF);
//         jTable2.setModel(DBUtils.resultSetTOTableModel(rs));
//
//        } catch (Exception e)
//        {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }
     public ArrayList<user2> userList(){
        ArrayList<user2> studentsList = new ArrayList<>();
         try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/qems?zeroDateTimeBehavior=CONVERT_TO_NULL","root","969276");
                System.out.println("Connected second");

                String query1="select * from students";
                
                Statement st = con.createStatement();
                ResultSet rs=st.executeQuery(query1);
                user2 user;
                while(rs.next()){
                    user= new user2(rs.getString("rollno"), rs.getString("name"), rs.getString("fathername"), rs.getString("gender"), rs.getString("contactno"), rs.getString("email"), rs.getString("tenthuniversityname"), rs.getString("tenthpercentage"), rs.getString("tenthpassoutyear"), rs.getString("twelveuniversityname"), rs.getString("twelvepercentage"), rs.getString("twelvepassoutyear"), rs.getString("graduationuniversityname"), rs.getString("graduationpercentage"), rs.getString("graduationpassoutyear"), rs.getString("adress"), rs.getString("marks"), rs.getString("subject"));
                   studentsList.add(user);
                }


            }
            catch(Exception e)
            {
                System.out.println("catch block...........");
                 return (null);
            }

                return studentsList;


    }
     public void show_users(){
        ArrayList<user2> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        Object[] row = new Object[18];
        for (int i=0;i<list.size();i++){
            row[0]=list.get(i).getrollno();
            row[1]=list.get(i).getname();
            row[2]=list.get(i).getfathername();
            row[3]=list.get(i).getgender();
            row[4]=list.get(i).getcontactno();
            row[5]=list.get(i).getemail();
            row[6]=list.get(i).gettenthuniversityname();
            row[7]=list.get(i).gettenthpercentage();
            row[8]=list.get(i).gettenthpassoutyear();
            row[9]=list.get(i).gettwelveuniversityname();
            row[10]=list.get(i).gettwelvepercentage();
            row[11]=list.get(i).gettwelvepassoutyear();
            row[12]=list.get(i).getgraduationuniversityname();
            row[13]=list.get(i).getgraduationpercentage();
            row[14]=list.get(i).getgraduationpassoutyear();
            row[15]=list.get(i).getadress();
            row[16]=list.get(i).getmarks();
            row[17]=list.get(i).getsubject();
            
            
            model.addRow(row);
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all student result.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 40)); // NOI18N
        jLabel2.setText("all student result");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 13, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1426, 13, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 1539, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Filter Students By Marks");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 117, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 197, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RollNo", "Name", "Father Name", "Gender", "Contact No", "Email", "TenthUnivesity Name", "TenthPercentage", "TenthPassoutYear", "TwelthUniversityName", "TwelthPercentage", "TwelthPassoutYear", "GraduationUniversity", "GraduationPercentage", "GraduationPassoutYear", "Adress", "marks", "subject"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 1466, 630));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages background admin ok.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        admineHome.open=0;
        setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        int marks;
        if(jTextField1.getText().equals(""))
        {
            marks=0;
        }
        else
            marks=Integer.parseInt(jTextField1.getText());
        try
        {Connection con = ConnectionProvider.getCon();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("select *from students where marks is >="+marks+"");
         jTable2.setAutoResizeMode(jTable2.AUTO_RESIZE_OFF);
         jTable2.setModel(DbUtils.resultSetTOTableModel(rs));

        } catch (Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllStudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllStudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllStudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllStudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllStudentResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private static class DbUtils {

        private static TableModel resultSetTOTableModel(ResultSet rs) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public DbUtils() {
        }
    }
}
